name: CI/CD Backend
on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Maven依存関係キャッシュ（シークレットのログ出力なし）
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      # バックエンドビルド・テスト (Secretsを出力しない)
      - name: Build & Test backend
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app/backend \
            eclipse-temurin:17-jdk-alpine sh -c "apk add --no-cache maven && mvn clean package -DskipTests=false"

      # Dockerマルチステージビルド - シークレット出力なし
      - name: Docker Build (Multi-stage)
        run: |
          docker build -t my-backend:latest -f backend/Dockerfile .

      # Azure OIDC Login - シークレットを直接参照、ログ出力せず
      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR Login
        run: az acr login --name myappacrdev

      # ACRへのPush、Secretsは出力しない
      - name: Push Image
        run: |
          docker tag my-backend:latest myappacrdev.azurecr.io/my-backend:latest
          docker push myappacrdev.azurecr.io/my-backend:latest

      # App Serviceデプロイ
      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myapp-backend-dev'
          images: 'myappacrdev.azurecr.io/my-backend:latest'
